name: Build on Develop Branch

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my-image:latest .

      - name: Push Docker image to registry
        run: docker push my-registry/my-image:latest
